{% set name = "pdoc" %}
{% set version = "14.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mitmproxy/pdoc/archive/refs/tags/v{{ version }}.tar.gz
  # pdoc does not currently upload a distrobution (tar.gz) file to PyPi, so I'm
  # stuck using the github URL for now. I requested this to be fixed, and it is
  # accepted, I can switch to the follow url:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # Until then, I must manually download and check with "openssl sha256 <download file>"
  sha256: fa87026c9297de62cd9106efea525c457701bf4125b7faaf71fab22ca528ab2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pdoc = pdoc.__main__:cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jinja2 >=2.11.0
    - pygments >=2.12.0
    - markupsafe
    - astunparse

test:
  imports:
    - pdoc
  requires:
    - pip
  commands:
    - pip check
    - pdoc --help

about:
  home: https://pdoc.dev/
  summary: API Documentation for Python Projects
  description: |
    see our main page for more information
  license: Unlicense
  license_file: LICENSE
  doc_url: https://pdoc.dev/docs/pdoc.html
  dev_url: https://github.com/mitmproxy/pdoc

extra:
  recipe-maintainers:
    - jacksund
